# name: Deploy to Environment

# on:
#   push:
#     branches:
#       - dev
#       - qa
#       - prod

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.6.6

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v3
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1

#       - name: Terraform Init
#         run: terraform init
#         working-directory: ./terraform/${{ github.ref_name }}

#       - name: Terraform Plan
#         run: terraform plan
#         working-directory: ./terraform/${{ github.ref_name }}

#       - name: Terraform Apply
#         run: terraform apply -auto-approve
#         working-directory: ./terraform/${{ github.ref_name }}


### deploy-dev.yml
name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/dev
